### ISSUE TITLE
Wan2.1-T2V-1.3B 这个模型我的笔记本是4090  16G 的为啥运行老是报错

### ISSUE THREAD

**Issue by anstonjie** [Wan-Video/Wan2.1#149]
运行命令python generate.py  --task t2v-1.3B --size 832*480 --ckpt_dir ./Wan2.1-T2V-1.3B --offload_model True --t5_cpu --sample_shift 8 --sample_guide_scale 6 --prompt "Two anthropomorphic cats in comfy boxing gear and bright gloves fight intensely on a spotlighted stage."

报错如下
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by aspatic** [comment]
不应该啊 4090 跑1.3B峰值显存占用不是只有9个G吗 
[](https://github.com/Wan-Video/Wan2.1/blob/main/assets/comp_effic.png)

你是不是后台不止在跑这个任务

**Comment by aspatic** [comment]
--t5_cpu 去掉能跑吗

**Comment by able2608** [comment]
> 运行命令python generate.py --task t2v-1.3B --size 832*480 --ckpt_dir ./Wan2.1-T2V-1.3B --offload_model True --t5_cpu --sample_shift 8 --sample_guide_scale 6 --prompt "Two anthropomorphic cats in comfy boxing gear and bright gloves fight intensely on a spotlighted stage."
> 
> 报错如下 RuntimeError: CUDA error: out of memory CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Is it possible that you paste the full stack traceback here so that we can see what stage (text encoding, diffusion, or VAE decoding) causes the error? To my knowledge the most VRAM intensive stage is at VAE decoding, but it might not be the case for you, and the full stack traceback can make debugging a lot easier.

> 估计是T5XXL太大了，你的cpu内存不够。

That seems to not be the case. The error originated from CUDA, not from the operating system. Plus I can run the T5 provided by the official repo on just 16GBs of system RAM.

> --t5_cpu 去掉能跑吗

It might not fix your OOM problem, but if the OOM problem is fixed it might boost the generation speed as text encoding will be done on GPU, which is faster. You can give it a try after your OOM problem is fixed and switch it back on if it doesn't work.
