### ISSUE TITLE
[5090D]RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by kekekekekeshi** [Wan-Video/Wan2.1#456]
python t2v_1.3B_singleGPU.py --prompt_extend_method 'local_qwen' --ckpt_dir ../Wan2.1-T2V-1.3B
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 303.78it/s]
done
Step2: Init 1.3B t2v model...done
* Running on local URL:  http://0.0.0.0:7860
* To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/gradio/queueing.py", line 626, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/gradio/blocks.py", line 2220, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/gradio/blocks.py", line 1731, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/gradio/utils.py", line 940, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/eashion/Wan2.1/gradio/t2v_1.3B_singleGPU.py", line 27, in prompt_enc
    prompt_output = prompt_expander(prompt, tar_lang=tar_lang.lower())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/Wan2.1/wan/utils/prompt_extend.py", line 152, in __call__
    return self.extend(prompt, system_prompt, seed, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/Wan2.1/wan/utils/prompt_extend.py", line 390, in extend
    generated_ids = self.model.generate(**model_inputs, max_new_tokens=512)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/transformers/generation/utils.py", line 2394, in generate
    self._prepare_special_tokens(generation_config, kwargs_has_attention_mask, device=device)
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/transformers/generation/utils.py", line 2169, in _prepare_special_tokens
    and isin_mps_friendly(elements=eos_token_tensor, test_elements=pad_token_tensor).any()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.12/site-packages/transformers/pytorch_utils.py", line 338, in isin_mps_friendly
    return torch.isin(elements, test_elements)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

  2%|████▏                                                                                                                                                                                                          | 1/50 [06:33<5:21:08, 393.23s/it]


**Now it directly degenerates to pure CPU running, why is this**

**Comment by kekekekekeshi** [comment]
我的锅，这个问题我解决了，大家可以往这里看。但是由于我把wan2.1 for mac项目拷贝到了x86，我折腾了两天终于想明白为啥cpu都干冒烟了结果cuda连风扇都没转。在此做个记录解决过程，希望对大家有用。请叫我活雷锋。

<img width="1380" alt="Image" src="https://github.com/user-attachments/assets/7e0167bc-7c47-46fa-bb67-94c1a8265bad" />
此时我重新安装依赖发现死活没有torch。当我安装了torch后仍然是这个结果。然后把这个贴给AI，然后它给出了方案：

> (wan2.1) eashion@eashion-CVN-Z890M-GAMING-FROZEN-V20:~/Wan2.1$ pip install -r requirements.txt
Requirement already satisfied: torch>=2.4.0 in /home/eashion/.pyenv/versions/wan2.1/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (2.7.1+cu128)
Requirement already satisfied: torchvision>=0.19.0 in /home/eashion/.pyenv/versions/wan2.1/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (0.22.1+cu128)
Collecting opencv-python>=4.9.0.80 (from -r requirements.txt (line 3))
  Using cached opencv_python-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting diffusers>=0.31.0 (from -r requirements.txt (line 4))
  Using cached diffusers-0.34.0-py3-none-any.whl.metadata (20 kB)
Collecting transformers>=4.49.0 (from -r requirements.txt (line 5))
  Using cached transformers-4.53.0-py3-none-any.whl.metadata (39 kB)
Collecting tokenizers>=0.20.3 (from -r requirements.txt (line 6))
  Using cached tokenizers-0.21.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting accelerate>=1.1.1 (from -r requirements.txt (line 7))
  Using cached accelerate-1.8.1-py3-none-any.whl.metadata (19 kB)
Collecting tqdm (from -r requirements.txt (line 8))
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting imageio (from -r requirements.txt (line 9))
  Using cached imageio-2.37.0-py3-none-any.whl.metadata (5.2 kB)
Collecting easydict (from -r requirements.txt (line 10))
  Using cached easydict-1.13-py3-none-any.whl.metadata (4.2 kB)
Collecting ftfy (from -r requirements.txt (line 11))
  Using cached ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Collecting dashscope (from -r requirements.txt (line 12))
  Using cached dashscope-1.23.6-py3-none-any.whl.metadata (7.1 kB)
Collecting imageio-ffmpeg (from -r requirements.txt (line 13))
  Using cached imageio_ffmpeg-0.6.0-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting flash_attn (from -r requirements.txt (line 14))
  Using cached flash_attn-2.8.0.post2.tar.gz (7.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/eashion/.pyenv/versions/wan2.1/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7waagjjh/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7waagjjh/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-7waagjjh/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 512, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-7waagjjh/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
        File "<string>", line 22, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(wan2.1) eashion@eashion-CVN-Z890M-GAMING-FROZEN-V20:~/Wan2.1$ python -c 'import torch; print(torch__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'torch__version__' is not defined
(wan2.1) eashion@eashion-CVN-Z890M-GAMING-FROZEN-V20:~/Wan2.1$ python -c 'import torch; print(torch.__version__)'
2.7.1+cu128
这是解决方案：
`pip install torch==2.7.1+cu128 --extra-index-url https://download.pytorch.org/whl/cu128`
然后安装`pip install flash-attn --no-cache-dir`
如果这个有问题就安装`   pip install flash-attn --no-build-isolation`
此时仍然有问题：

<img width="1344" alt="Image" src="https://github.com/user-attachments/assets/c1d2442b-e83e-430d-a20a-5457ff6d3a36" />
此时我安装`pip install packaging`
仍然有问题：

<img width="1343" alt="Image" src="https://github.com/user-attachments/assets/e024be82-b8a8-4481-9b3c-e964c3f7d115" />
接着安装呗：`pip install wheel`
安装完这个在安装` pip install flash-attn --no-build-isolation && pip install -r requirements.txt`
然后搞定了。
