### ISSUE TITLE
GPU 4090：使用界面 gradio/t2v_1.3B_singleGPU.py  生成一个 480*832的视频， steps 50/50后显示显存存不够用

### ISSUE THREAD

**Issue by dingquanbin** [Wan-Video/Wan2.1#52]
(wan2.1) root@misui:/home/misui/py-ws/Wan2.1# DASH_API_KEY=**************** python gradio/t2v_1.3B_singleGPU.py --prompt_extend_method 'dashscope'  --ckpt_dir /home/misui/py-ws/Wan2.1/Wan2.1-T2V-1.3B
Step1: Init prompt_expander...done
Step2: Init 1.3B t2v model...done
* Running on local URL:  http://0.0.0.0:8760

To create a public link, set `share=True` in `launch()`.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [04:08<00:00,  4.98s/it]
Traceback (most recent call last):
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/gradio/queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/gradio/blocks.py", line 2096, in process_api
    result = await self.call_function(
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/gradio/blocks.py", line 1643, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2461, in run_sync_in_worker_thread
    return await future
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 962, in run
    result = context.run(func, *args)
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/gradio/utils.py", line 890, in wrapper
    response = f(*args, **kwargs)
  File "/home/misui/py-ws/Wan2.1/gradio/t2v_1.3B_singleGPU.py", line 40, in t2v_generation
    video = wan_t2v.generate(
  File "/home/misui/py-ws/Wan2.1/wan/text2video.py", line 256, in generate
    videos = self.vae.decode(x0)
  File "/home/misui/py-ws/Wan2.1/wan/modules/vae.py", line 659, in decode
    return [
  File "/home/misui/py-ws/Wan2.1/wan/modules/vae.py", line 660, in <listcomp>
    self.model.decode(u.unsqueeze(0),
  File "/home/misui/py-ws/Wan2.1/wan/modules/vae.py", line 562, in decode
    out_ = self.decoder(
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/misui/py-ws/Wan2.1/wan/modules/vae.py", line 451, in forward
    x = layer(x, feat_cache, feat_idx)
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/misui/py-ws/Wan2.1/wan/modules/vae.py", line 215, in forward
    x = layer(x, feat_cache[idx])
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/misui/py-ws/Wan2.1/wan/modules/vae.py", line 34, in forward
    x = F.pad(x, padding)
  File "/home/misui/anaconda3/envs/wan2.1/lib/python3.10/site-packages/torch/nn/functional.py", line 5209, in pad
    return torch._C._nn.pad(input, pad, mode, value)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 884.00 MiB. GPU 0 has a total capacity of 23.64 GiB of which 28.19 MiB is free. Including non-PyTorch memory, this process has 23.54 GiB memory in use. Of the allocated memory 21.27 GiB is allocated by PyTorch, and 1.78 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by dingquanbin** [comment]
使用 命令行就不存在这个问题，python generate.py  --task t2v-1.3B --size 480*832 --ckpt_dir ./Wan2.1-T2V-1.3B  --sample_shift 8 --sample_guide_scale 6 --prompt "****"

**Comment by kangzhao2** [comment]
你可以把 https://github.com/Wan-Video/Wan2.1/blob/main/gradio/t2v_1.3B_singleGPU.py#L49 改成True试试

**Comment by therestlife** [comment]
我也遇到了 显存临界值 生成完毕之后导出的时候还需要占用显存   我加了个环境变量解决了  export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True    另外你还可以改变step t2v不一定非得50

**Comment by dingquanbin** [comment]
> 你可以把 https://github.com/Wan-Video/Wan2.1/blob/main/gradio/t2v_1.3B_singleGPU.py#L49 改成True试试

这样或不会降低生成的效果

**Comment by kangzhao2** [comment]
> > 你可以把 https://github.com/Wan-Video/Wan2.1/blob/main/gradio/t2v_1.3B_singleGPU.py#L49 改成True试试
> 
> 这样或不会降低生成的效果

不会。我们已经把 https://github.com/Wan-Video/Wan2.1/blob/main/gradio/t2v_1.3B_singleGPU.py#L49 修复了，你可以测一下

**Comment by kangzhao2** [comment]
> Hi [@kangzhao2](https://github.com/kangzhao2) I am trying it now with 12Gb VRAM with a 3060, I am still getting the error. torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 444.00 MiB. GPU 0 has a total capacity of 11.65 GiB of which 243.88 MiB is free. Including non-PyTorch memory, this process has 11.40 GiB memory in use. Of the allocated memory 9.99 GiB is allocated by PyTorch, and 1.28 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) This is the same running it via gradio or via the generate.py command line. Is there something I am missing? Please help

If your GPU memory is lower than that of 4090, you can try to set t5_cpu=True after https://github.com/Wan-Video/Wan2.1/blob/main/gradio/t2v_1.3B_singleGPU.py#L202

**Comment by lcax200000** [comment]
8x4090rtx 24G上运行14b-FP16一样出现vae oom的情况  @kangzhao2 

torchrun --nproc_per_node=8 generate.py --task i2v-14B --size 720*1280 --ckpt_dir models/Wan2.1-I2V-14B-720P-FP16   --t5_cpu   --dit_fsdp --t5_fsdp --ulysses_size 8   --offload_model True   --sample_steps=20 --image examples/i2v_input.JPG --dit_fsdp --t5_fsdp --ulysses_size 8 --prompt "Summer beach vacation style, a white cat wearing sunglasses sits on a surfboard. The fluffy-furred feline gazes directly at the camera with a relaxed expression. Blurred beach scenery forms the background featuring crystal-clear waters, distant green hills, and a blue sky dotted with white clouds. The cat assumes a naturally relaxed posture, as if savoring the sea breeze and warm sunlight. A close-up shot highlights the feline's intricate details and the refreshing atmosphere of the seaside." 
W0322 10:56:28.938000 203394 torch/distributed/run.py:793] 
W0322 10:56:28.938000 203394 torch/distributed/run.py:793] *****************************************
W0322 10:56:28.938000 203394 torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0322 10:56:28.938000 203394 torch/distributed/run.py:793] *****************************************
DEBUG 03-22 10:56:35 [parallel_state.py:200] world_size=8 rank=0 local_rank=-1 distributed_init_method=env:// backend=nccl
DEBUG 03-22 10:56:35 [parallel_state.py:200] world_size=8 rank=1 local_rank=-1 distributed_init_method=env:// backend=nccl
DEBUG 03-22 10:56:35 [parallel_state.py:200] world_size=8 rank=5 local_rank=-1 distributed_init_method=env:// backend=nccl
DEBUG 03-22 10:56:35 [parallel_state.py:200] world_size=8 rank=3 local_rank=-1 distributed_init_method=env:// backend=nccl
DEBUG 03-22 10:56:35 [parallel_state.py:200] world_size=8 rank=2 local_rank=-1 distributed_init_method=env:// backend=nccl
DEBUG 03-22 10:56:35 [parallel_state.py:200] world_size=8 rank=6 local_rank=-1 distributed_init_method=env:// backend=nccl
DEBUG 03-22 10:56:35 [parallel_state.py:200] world_size=8 rank=7 local_rank=-1 distributed_init_method=env:// backend=nccl
DEBUG 03-22 10:56:35 [parallel_state.py:200] world_size=8 rank=4 local_rank=-1 distributed_init_method=env:// backend=nccl
[2025-03-22 10:56:35,989] INFO: Generation job args: Namespace(task='i2v-14B', size='720*1280', frame_num=81, ckpt_dir='models/Wan2.1-I2V-14B-720P-FP16', offload_model=True, ulysses_size=8, ring_size=1, t5_fsdp=True, t5_cpu=True, dit_fsdp=True, save_file=None, prompt="Summer beach vacation style, a white cat wearing sunglasses sits on a surfboard. The fluffy-furred feline gazes directly at the camera with a relaxed expression. Blurred beach scenery forms the background featuring crystal-clear waters, distant green hills, and a blue sky dotted with white clouds. The cat assumes a naturally relaxed posture, as if savoring the sea breeze and warm sunlight. A close-up shot highlights the feline's intricate details and the refreshing atmosphere of the seaside.", use_prompt_extend=False, prompt_extend_method='local_qwen', prompt_extend_model=None, prompt_extend_target_lang='zh', base_seed=5129271660254883081, image='examples/i2v_input.JPG', sample_solver='unipc', sample_steps=20, sample_shift=5.0, sample_guide_scale=5.0)
[2025-03-22 10:56:35,989] INFO: Generation model config: {'__name__': 'Config: Wan I2V 14B', 't5_model': 'umt5_xxl', 't5_dtype': torch.bfloat16, 'text_len': 512, 'param_dtype': torch.bfloat16, 'num_train_timesteps': 1000, 'sample_fps': 16, 'sample_neg_prompt': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走', 't5_checkpoint': 'models_t5_umt5-xxl-enc-bf16.pth', 't5_tokenizer': 'google/umt5-xxl', 'clip_model': 'clip_xlm_roberta_vit_h_14', 'clip_dtype': torch.float16, 'clip_checkpoint': 'models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth', 'clip_tokenizer': 'xlm-roberta-large', 'vae_checkpoint': 'Wan2.1_VAE.pth', 'vae_stride': (4, 8, 8), 'patch_size': (1, 2, 2), 'dim': 5120, 'ffn_dim': 13824, 'freq_dim': 256, 'num_heads': 40, 'num_layers': 40, 'window_size': (-1, -1), 'qk_norm': True, 'cross_attn_norm': True, 'eps': 1e-06}
[2025-03-22 10:56:36,747] INFO: Input prompt: Summer beach vacation style, a white cat wearing sunglasses sits on a surfboard. The fluffy-furred feline gazes directly at the camera with a relaxed expression. Blurred beach scenery forms the background featuring crystal-clear waters, distant green hills, and a blue sky dotted with white clouds. The cat assumes a naturally relaxed posture, as if savoring the sea breeze and warm sunlight. A close-up shot highlights the feline's intricate details and the refreshing atmosphere of the seaside.
[2025-03-22 10:56:36,747] INFO: Input image: examples/i2v_input.JPG
[2025-03-22 10:56:36,785] INFO: Creating WanI2V pipeline.
[2025-03-22 10:57:51,725] INFO: loading /data/usp/ComfyUI/models/Wan2.1-I2V-14B-720P-FP16/models_t5_umt5-xxl-enc-bf16.pth
[2025-03-22 10:58:19,304] INFO: loading /data/usp/ComfyUI/models/Wan2.1-I2V-14B-720P-FP16/Wan2.1_VAE.pth
[2025-03-22 10:58:20,281] INFO: loading /data/usp/ComfyUI/models/Wan2.1-I2V-14B-720P-FP16/models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth
[2025-03-22 10:58:33,278] INFO: Creating WanModel from /data/usp/ComfyUI/models/Wan2.1-I2V-14B-720P-FP16
[2025-03-22 11:03:53,936] INFO: Generating video ...
[rank5]: Traceback (most recent call last):
[rank5]:   File "/data/usp/Wan2.1/generate.py", line 428, in <module>
[rank5]:     generate(args)
[rank5]:   File "/data/usp/Wan2.1/generate.py", line 384, in generate
[rank5]:     video = wan_i2v.generate(
[rank5]:   File "/data/usp/Wan2.1/wan/image2video.py", line 239, in generate
[rank5]:     y = self.vae.encode([
[rank5]:   File "/data/usp/Wan2.1/wan/modules/vae.py", line 652, in encode
[rank5]:     return [
[rank5]:   File "/data/usp/Wan2.1/wan/modules/vae.py", line 653, in <listcomp>
[rank5]:     self.model.encode(u.unsqueeze(0), self.scale).float().squeeze(0)
[rank5]:   File "/data/usp/Wan2.1/wan/modules/vae.py", line 530, in encode
[rank5]:     out_ = self.encoder(
[rank5]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank5]:     return forward_call(*args, **kwargs)
[rank5]:   File "/data/usp/Wan2.1/wan/modules/vae.py", line 338, in forward
[rank5]:     x = layer(x, feat_cache, feat_idx)
[rank5]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank5]:     return forward_call(*args, **kwargs)
[rank5]:   File "/data/usp/Wan2.1/wan/modules/vae.py", line 215, in forward
[rank5]:     x = layer(x, feat_cache[idx])
[rank5]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank5]:     return forward_call(*args, **kwargs)
[rank5]:   File "/data/usp/Wan2.1/wan/modules/vae.py", line 34, in forward
[rank5]:     x = F.pad(x, padding)
[rank5]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 5096, in pad
[rank5]:     return torch._C._nn.pad(input, pad, mode, value)
[rank5]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 5 has a total capacity of 23.55 GiB of which 1.26 GiB is free. Including non-PyTorch memory, this process has 22.27 GiB memory in use. Of the allocated memory 19.64 GiB is allocated by PyTorch, and 2.04 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
